# Generated by Django 5.2.12 on 2026-03-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='is_avialable',
            new_name='is_available',
        ),
    ]
